version: "3.8"
services:
  elixir_dev:
    build: .
    image: elixir_dev_custom
    env_file:
      - .env
    volumes:
      - .:/workspace # Mounts the current directory to /workspace inside the container
    ports:
      - "4000:4000"
    working_dir: /workspace
    stdin_open: true # Keeps stdin open
    tty: true # Allows an interactive terminal
    depends_on:
      - postgres # Ensure postgres service starts first
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
volumes:
  pgdata:
